apiVersion: v1
kind: Namespace
metadata:
  name: k4s-demo
  labels:
    app.kubernetes.io/part-of: k4s-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: k4s-broken
  labels:
    app.kubernetes.io/part-of: k4s-demo
